---
title: "Tensor Flo Ridas: A Journey in ML"
output: 
  html_document: 
    toc: TRUE
    toc_depth: 1
    toc_float: TRUE
    number_sections: TRUE
    code_folding: hide
    df_print: paged
---

```{r setup, include = FALSE}
# set chunk options
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE,
                      cache = TRUE)

# load packages
library(tidyverse)
library(tidymodels)
library(baguette)
library(future)
library(vip)
library(rpart.plot)
library(here)
library(rio)
library(magrittr)

# create theme
theme_407 <- function() { 
    theme_bw(base_size = 5) %+replace% 
        theme(
          legend.direction = "horizontal",
          legend.background = element_rect(fill = "#1b1d22",
                                           colour = "#1b1d22"),
          panel.background = element_rect(fill = "#171f24",
                              colour = "#1b1d22",
                              size = 0.5, linetype = "solid"),
          panel.grid.major = element_line(size = 0.2, 
                                          linetype = 'solid', 
                                          colour = "gray40"), 
          panel.grid.minor = element_line(size = 0.0, 
                                          linetype = 'solid',
                                          colour = "gray40"),
          axis.line = element_line(colour = "white"),
          plot.background = element_rect(fill = "#171f24"),
          text  = element_text(color = "white", size = 1),
          axis.text  = element_text(color = "white"),
          axis.ticks = element_line(color = "white"),
          strip.background = element_rect(fill = "white",
                                          colour = "white")
        )
}

# import all data
set.seed(3000)

data <- import(here::here("data", "data.csv"), setclass = "tibble") %>%
  janitor::clean_names() %>%
  sample_frac(.001)

# split data
set.seed(3000)

data_split    <- initial_split(data)

data_train    <- training(data_split)

data_test     <- testing(data_split)

data_train_cv <- vfold_cv(data_train)

# create recipe
recipe_1 <- recipe(score ~ ., data_train) %>%  
    step_mutate(tst_dt = lubridate::mdy_hm(tst_dt)) %>%
    update_role(contains("id"), ncessch, sch_name, new_role = "id vars") %>%
    step_novel(all_nominal()) %>%
    step_unknown(all_nominal()) %>%
    step_zv(all_predictors()) %>%
    step_normalize(all_numeric(), -all_outcomes(), -has_role("id vars")) %>%
    step_BoxCox(all_numeric(), -all_outcomes(), -has_role("id vars")) %>%
    step_medianimpute(all_numeric(), -all_outcomes(), -has_role("id vars")) %>%
    step_dummy(all_nominal(), -has_role("id vars"), one_hot = TRUE) %>%
    step_zv(all_predictors())

```

***

# Create the model

Here is how I created the model. It is all quite impressive. 

```{r}
model_rf <- rand_forest() %>% 
  set_mode("regression") %>% 
  set_engine(engine      = "ranger",
             num.threads = parallel::detectCores() - 2,
             importance  = "permutation",
             verbose     = TRUE) %>% 
  set_args(trees = 1000)
```

# Create workflow object

Here is how I created the workflow. One cannot doubt my greatness.

```{r}
# create workflow object
workflow_rf <- workflow() %>% 
  add_recipe(recipe_1) %>% 
  add_model(model_rf)
```

# Run random forest model

I am the creator of worlds (or, at the very least, forests). 

```{r}
# start timer
tictoc::tic()

# fit model
fit_rf <- fit_resamples(
  object    = workflow_rf,
  resamples = data_train_cv,
  metrics   = yardstick::metric_set(rmse, rsq, huber_loss),
  control   = control_resamples(verbose   = TRUE,
                                save_pred = TRUE,
                                extract   = function(x) extract_model(x)))

# end timer
tictoc::toc()

```

# Extract important predictors

...axis labels still somehow elude me. 

```{r}
pluck(fit_rf, ".extracts", 1, ".extracts", 1) %>%
  vip(aesthetics = list(fill = "cyan3")) +
  labs(x = "Predictor") + 
  theme_407()

```


***

<center>
*Last updated: December 2nd, 2020.*
</center>